"use client";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { useState } from "react";
import { Transaction } from "@solana/web3.js";
import { drawIx, initPlayerIx, parsePlayer, playerPda } from "../lib/program";
const labels=["彩虹贴纸","小小奖牌","故事时间","神秘礼物"];
export default function Home(){const {connection}=useConnection();const wallet=useWallet();const [game,setGame]=useState<0|1>(0);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("连接钱包后，今天可以玩一次");
async function play(){if(!wallet.publicKey||!wallet.sendTransaction)return;setBusy(true);try{const p=playerPda(wallet.publicKey);const info=await connection.getAccountInfo(p);const tx=new Transaction();if(!info)tx.add(initPlayerIx(wallet.publicKey));tx.add(drawIx(wallet.publicKey,game));const sig=await wallet.sendTransaction(tx,connection);setMsg(`随机数请求已发送：${sig.slice(0,8)}… 正在等待公平结果`);await connection.confirmTransaction(sig,"confirmed");setTimeout(async()=>{const next=await connection.getAccountInfo(p);if(next){const state=parsePlayer(Buffer.from(next.data));setMsg(state.status===2?`恭喜你获得：${labels[state.prize]||`奖品 ${state.prize+1}`}！`:"魔法正在生成，请稍后刷新")}},3000)}catch(e){setMsg(e instanceof Error?e.message:"交易失败")}finally{setBusy(false)}}
return <main><header><div><span className="eyebrow">SOLANA DEVNET · 公平随机</span><h1>幸运花园</h1><p>每天一次小惊喜，开心玩、不花钱。</p></div><WalletMultiButton /></header><section className="tabs" aria-label="选择游戏"><button className={game===0?"active":""} onClick={()=>setGame(0)}>转盘抽奖</button><button className={game===1?"active":""} onClick={()=>setGame(1)}>对对碰</button></section><section className="game"><div className={game===0?"wheel":"cards"} aria-hidden="true">{game===0?<><span>故事</span><span>贴纸</span><span>奖牌</span><span>礼物</span></>:Array.from({length:8},(_,i)=><i key={i}>{i%2?"★":"●"}</i>)}</div><div><h2>{game===0?"转动幸运转盘":"翻开欢乐卡片"}</h2><p>{game===0?"由链上可验证随机数选出今天的惊喜。":"完成可爱配对，再揭晓今天的惊喜。"}</p><button className="play" disabled={!wallet.connected||busy} onClick={play}>{busy?"正在施展魔法…":wallet.connected?"开始今天的游戏":"请先连接钱包"}</button><output aria-live="polite">{msg}</output></div></section><footer>规则透明 · 每个钱包每个 UTC 自然日一次 · 不收集儿童个人信息</footer></main>}
